const EVENT_STARTED = 'EVENT_STARTED';
module.exports.EVENT_STARTED = EVENT_STARTED;

const EVENT_REQUEST = 'EVENT_REQUEST';
module.exports.EVENT_REQUEST = EVENT_REQUEST;

const EVENT_RESPONSE = 'EVENT_RESPONSE';
module.exports.EVENT_RESPONSE = EVENT_RESPONSE;
