const EVENT_STARTED = 'LAMBDA_EVENT_STARTED';
module.exports.EVENT_STARTED = EVENT_STARTED;

const EVENT_REQUEST = 'LAMBDA_EVENT_REQUEST';
module.exports.EVENT_REQUEST = EVENT_REQUEST;

const EVENT_RESPONSE = 'LAMBDA_EVENT_RESPONSE';
module.exports.EVENT_RESPONSE = EVENT_RESPONSE;
